project: llm_behavior_trading
data:
  use_processed: true
  use_gcs: true
  use_local: false
  use_polygon: false
  event_stride_minutes: 5
  gcs:
    bucket: jwss_data_store
    root: stocks
    use_gcsfs: true
  schema:
    timestamp: t
    open: o
    high: h
    low: l
    close: c
    volume: v
    ticker: ticker

sessions:
  tz: America/New_York
  rth_start: "09:30"
  rth_end: "16:00"
  eod_flat_minutes_before_close: 1

risk:
  start_equity: 10000
  risk_perc: 0.02
  max_trades_per_day: 5
  atr_stop_mult: 1.5
  take_profit_R: 2.0
  slippage_cents: 1
  commission_per_share: 0.005

features:
  atr_window: 20
  rvol_windows: [5, 20]
  volume_profile:
    bin_size: 0.05
    value_area: 0.70
    rolling_sessions: 20
  ict:
    fvg_min_size_atr: 0.25
    displacement_body_atr: 1.2
  vpa:
    rvol_climax: 2.5
    vdu_threshold: 0.4
    atr_threshold: 0.5
    breakout_lookback: 20
  enable:
    ta: true
    volume_profile: true
    vpa: true
    ict: true
    time_of_day: true
    vwap: true

time_of_day:
  killzones:
    ny_open: ["09:30","11:30"]
    lunch: ["12:00","13:30"]
    pm_drive: ["13:30","16:00"]

horizons_minutes: [5, 15, 30, 60, 120, 240]

cv:
  walk_forward:
    train_months: 24
    val_months: 1
    embargo_days: 5
  ticker_holdout: 20

model:
  type: xgboost
  params:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    tree_method: hist  # Memory efficient for large datasets
    n_jobs: 8  # Use all 8 cores
    random_state: 42

tickers:
  train: [
    AAPL, MSFT, AMZN, GOOGL, META, NFLX, NVDA, AMD, INTC, MU, QCOM, AVGO, TXN, ADI, KLAC, 
    LRCX, TSM, ASML, MRVL, NXPI, ON, ARM, SHOP, CRM, MDB, SNOW, NOW, DDOG, OKTA, ZS, NET, 
    PANW, CRWD, RBLX, U, PLTR, PATH, AFRM, SQ, PYPL, COIN, HOOD, SOFI, DKNG, PENN, MGM, 
    CCL, NCLH, RCL, UAL, DAL, AAL, LUV, JBLU, LYV, PEP, KO, MCD, SBUX, CMG, WEN, YUM, WMT, 
    TGT, COST, HD, LOW, BBY, NKE, LULU, CROX, HBI, KSS, ANF, URBN, GPS, AEO, ELYV, F, GM, 
    STLA, TSLA, RIVN, LCID, NIO, XPEV, LI, UBER, LYFT, DASH, ABNB, BKNG, MAR, HLT, ARMK, 
    CHWY, ETSY, EBAY, W, PDD, BABA, JD, BIDU, IQ, TME, BILI, SE, MELI, NU, GLBE, PDD, TTD, 
    ROKU, DIS, WBD, PARA, FOXA, SONY, EA, TTWO, ATVI, HAS, MAT, BYND, KHC, CPB, GIS, SJM, 
    CAG, K, KR, DG, DLTR, FIVE, OLLI, SIG, ROST, TJX, M, JWN, BBWI, WOOF, WW, BKE, AAP, 
    AZO, ORLY, GME, AMC
  ]
  oos: [
    REGN, LLY, TMO, MDT, BMY, BKNG, MAR, DHI, LEN, PLD, AMT, O, SPG, EOG, DUK, SO, TMUS, KR, AIG, MET
  ]