llm:
  provider: openrouter
  base_url: https://openrouter.ai/api/v1
  api_key_env: OPENROUTER_API_KEY
  model: z-ai/glm-4.5
  headers:
    HTTP-Referer: http://localhost
    X-Title: codex-cli
  reasoning:
    enabled: true
